# Generated by Django 4.2.7 on 2023-12-01 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('service_title', models.CharField(max_length=200)),
                ('service_info', models.CharField(max_length=200)),
                ('service_cost', models.CharField(max_length=200)),
                ('service_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=50)),
                ('review_rating', models.IntegerField()),
                ('review_comments', models.CharField(max_length=500)),
                ('review_image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='website.service')),
            ],
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_ID', models.CharField(max_length=50)),
                ('contact_first_name', models.CharField(max_length=200)),
                ('contact_last_name', models.CharField(max_length=200)),
                ('contact_preferredService', models.CharField(max_length=200)),
                ('usr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.CharField(max_length=200)),
                ('invoice_total', models.CharField(max_length=200)),
                ('invoice_description', models.CharField(max_length=200)),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='website.service')),
            ],
        ),
    ]
