# Generated by Django 4.2.6 on 2023-12-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_review_service_id_remove_service_serv_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='website.service'),
        ),
    ]
